### ISSUE TITLE
Message Limit - #9

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-11/chatty-waterwheels#7]
## User Story
As a user, I have a short attention span, and only want to see the last 20 messages.

## AC
**Given** A user navigates to your page
**Then** they should only see the last 20 messages

## Dev Notes
- [x] inside `src/javascripts/components` create a new file called `messageLimit.js`
- [x] import `messageData.js`
- [x] create a new function named `showTwentyMessages`

This function should:
- [x] check the length of messages array with an `if statement` (if messages.length > 20, then use `.shift` method to remove the first message)
- [x] export the function and add into `addNewMessage` (needs to be called between the code that pushes the new message, and the call of `displayAllMessages`

(To sum: addNewMessage already takes in new messages, then will use showTwentyMessages to compare the length, then will displayAllMessages)

**Comment by spookycutie08** [comment]
I could not get this feature to work with another component .js page... it also seemed a little redundant because the only purpose would be to call the setter.  So I built the setter (limiting 20 messages) directly into messageData.js, and then called it directly in the addNew Message function of newMessage.js
